import scrapy

class MatchStatsItem(scrapy.Item):
    week = scrapy.Field()
    stadium = scrapy.Field()

    home_team = scrapy.Field()
    home_score = scrapy.Field()
    home_possession = scrapy.Field()
    home_shot_on_target = scrapy.Field()
    home_shot = scrapy.Field()
    home_shot_accuracy = scrapy.Field()
    home_pass_success = scrapy.Field()
    home_pass_fail = scrapy.Field()
    home_corner_kick = scrapy.Field()
    home_tackle_success = scrapy.Field()
    home_offside = scrapy.Field()
    home_foul = scrapy.Field()
    home_yellow_card = scrapy.Field()
    home_red_card = scrapy.Field()

    away_team = scrapy.Field()
    away_score = scrapy.Field()
    away_possession = scrapy.Field()
    away_shot_on_target = scrapy.Field()
    away_shot = scrapy.Field()
    away_shot_accuracy = scrapy.Field()
    away_pass_success = scrapy.Field()
    away_pass_fail = scrapy.Field()
    away_corner_kick = scrapy.Field()
    away_tackle_success = scrapy.Field()
    away_offside = scrapy.Field()
    away_foul = scrapy.Field()
    away_yellow_card = scrapy.Field()
    away_red_card = scrapy.Field()
